### ISSUE TITLE
Plugin is not loading variables

### ISSUE THREAD

**Issue by UgoJau** [lauthieb/variables-converter-figma-plugin#8] opened 2023-07-18 08:27 UTC
Hi,

I tried with various files, on Figma Beta and Figma.
I can't find a reason why it's not working on some files.

Video to see what it does :
https://github.com/lauthieb/variables-converter-figma-plugin/assets/63340174/2a793b2b-d2a4-4f64-b095-be278837d440

Same issue as [@trunglu](https://www.figma.com/@trunglu)

**Comment by lauthieb** [comment] 2023-07-18 20:15
Thanks @UgoJau 
That's completely weird, I cannot reproduce on my side.
Is it possible for you to send an email with this video to support@figma.com please?
Feel free also to screenshot the console 🙏

**Comment by SpruceCarbon** [comment] 2023-08-01 16:36
Thx, 
Done 
I could may be share a a file in private so you could dig in ?

**Comment by SpruceCarbon** [comment] 2023-08-01 16:43
On peux aussi continuer en français en fait ;)
Voici le screenshot de la console
<img width="1728" alt="Capture d’écran 2023-08-01 à 18 39 37" src="https://github.com/lauthieb/variables-converter-figma-plugin/assets/63340174/9ffb4c44-0b5c-427c-a218-c24ec3725fba">

**Comment by SpruceCarbon** [comment] 2023-08-01 16:46
The variables were generated by Tokens Studio, could this have something to do with it?
Some still have "?" aliases in LOCAL VARIABLES

**Comment by lauthieb** [comment] 2023-08-01 21:54
Hi @UgoJau,

Thanks for your screenshot and details (I prefer to continue in English in order to include other people in the resolution of this bug if it's ok for you).

Yes please can you let me check your file by adding me? 

My email: thiebault.laurent@gmail.com

Thank you!

**Comment by SpruceCarbon** [comment] 2023-08-02 08:44
Yes of course, no prob.

That's what I thought, it's linked with deleted or unfindable aliases variables now in an other collection.

<img width="277" alt="Capture d’écran 2023-08-02 à 10 36 29" src="https://github.com/lauthieb/variables-converter-figma-plugin/assets/63340174/5b4db844-02d0-4640-94bf-fc49865f974c">

It probably happened when we created variables with Tokens Studio.

So far I've duplicated a test file and deleted all unlinked variables and it works.

I will continue and let you know if works on the original file once it's all done.

If so I'll forward this conversation to Figma support to let them know as well.
Thx

**Comment by SpruceCarbon** [comment] 2023-08-02 09:51
It worked as planned :)

**Comment by SpruceCarbon** [comment] 2023-08-02 09:52
Thanks for your quick answers, nice work.

**Comment by lauthieb** [comment] 2023-08-02 09:55
@UgoJau, thank you very much! So, can I close this issue?

**Comment by SpruceCarbon** [comment] 2023-08-02 11:52
👌 @lauthieb

**Closed as completed** 2023-08-02 12:21 UTC
Labels: bug
